[project]
name = "jraph-mpeu"
version = "0.1.0"
description = "Graph neural networks in JAX for regression of atomistic structure-property relations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ase>=3.24.0",
    "dm-haiku>=0.0.13",
    "flax>=0.10.5",
    "jax>=0.5.3",
    "jraph>=0.0.6.dev0",
    "matscipy>=1.1.1",
    "ml-collections>=1.0.0",
    "parameterized>=0.9.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
]
